# Generated by Django 3.0.2 on 2020-01-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('created_at', models.DateField(verbose_name='Created_at')),
            ],
        ),
    ]
